spring.application.name=servico-auditor-dlq

# Server
server.port=8081

# Banco de dados H2
spring.datasource.url=jdbc:h2:mem:auditdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# AWS SQS - Credenciais diretas
cloud.aws.region.static=us-east-1
cloud.aws.credentials.access-key=AKIAVW6VLGVUDIGH33PW
cloud.aws.credentials.secret-key=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
cloud.aws.stack.auto=false

# Nome da DLQ
sqs.dlq.name=T03N-JOAO-PEDRO-FREITAS-DLQ.fifo

# Logging
logging.level.com.seudominio.auditor=DEBUG
logging.level.io.awspring.cloud.sqs=INFO
