spring.application.name=servico-auditor-dlq

# Server
server.port=8081

# Banco de dados H2
spring.datasource.url=jdbc:h2:mem:auditdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# AWS SQS - Usando variáveis de ambiente
cloud.aws.region.static=${AWS_REGION:us-east-1}
cloud.aws.credentials.access-key=${AWS_ACCESS_KEY_ID:}
cloud.aws.credentials.secret-key=${AWS_SECRET_ACCESS_KEY:}
cloud.aws.stack.auto=false

# Nome da DLQ
sqs.dlq.name=T03N-JOAO-PEDRO-FREITAS-DLQ.fifo

# Logging
logging.level.com.seudominio.auditor=INFO
logging.level.io.awspring.cloud.sqs=INFO
logging.level.software.amazon.awssdk=INFO